const reemplazos = {
    // Carreras profesionales (Pregrados)
    "PRE-GRADOS ADMINISTRACION DE EMPRESAS 2024": "Administración de Empresas",
    "PRE-GRADOS ARQUITECTURA IUDC 2024": "Arquitectura",
    "PRE-GRADOS COMUNICACION SOCIAL 2024": "Comunicación Social",
    "PRE-GRADOS CONTADURIA PUBLICA  2024": "Contaduría Pública",
    "PRE-GRADOS INGENIERÍA DE SISTEMAS 2024": "Ingeniería de Sistemas",
    "PRE-GRADOS INGENIERÍA DE SOFTWARE 2024": "Ingeniería de Software",
    "PRE-GRADOS INGENIERÍA INDUSTRIAL 2024": "Ingeniería Industrial",
    "PRE-GRADOS PSICOLOGÍA IUDC 2024": "Psicología",
    "PRE-GRADOS PSICOLOGÍA IUDC FDS V2": "Psicologia",
    "PRE-GRADOS DERECHO V1-2024": "Derecho",
    "PRE-GRADOS DERECHO FDS-V2": "Derecho",
    // Pregrados Generales...
    "PRE-GRADOS GENERAL-V2": "Pregrado",
    "PRE-GRADOS GENERAL": "Pregrado",
    "PRE-GRADOS DERECHO 2024": "Derecho",
    "PRE-GRADOS MEDICINA VET Y ZOO 2024": "Medicina Veterinaria y Zootecnia",
    "Medicina Veterinaria y Zootecnia-v2": "Medicina Veterinaria y Zootecnia",
    "PRE-GRADOS MEDICINA VET Y ZOO 2024-v2": "Medicina Veterinaria y Zootecnia",
    "PRE-GRADOS MEDICINA VET Y ZOO 2024": "Medicina Veterinaria y Zootecnia",
    "SU PROF Administración de Empresas 2024": "Administración de Empresas",
    "SU PROF Arquitectura 2024": "Arquitectura",
    "PRE-GRADOS ARQUITECTUTA FDS V2": "Arquitectura",
    "Arquitectura V2":"Arquitectura",
    "SU PROF Comunicación Social 2024": "Comunicación Social",
    "SU PROF Contaduría Pública 2024": "Contaduría Pública",
    "SU PROF Ingeniería de Sistemas 2024": "Ingeniería de Sistemas",
    "SU PROF Ingeniería de Software 2024": "Ingeniería de Software",
    "SU PROF Ingeniería Industrial 2024": "Ingeniería Industrial",
    "SU PROF Psicología 2024": "Psicología",
    "pre-grados Psicología 2024": "Psicología",
    "SU PROF Derecho 2024": "Derecho ",
    "PRE-GRADOS DERECHO FDS": "Derecho",
    "PRE-GRADOS PSICOLOGÍA IUDC FDS": "Psicología",
    "PRE-GRADOS INGENIERÍA DE SISTEMAS FDS": "Ingeniería de Sistemas",
    "PRE-GRADOS INGENIERÍA DE SOFTWARE FDS": "Ingeniería de Software",
    "PRE-GRADOS ARQUITECTUTA FDS": "Arquitectura",

    // Tecnicos
    "TÉCNICAS IUDC COMUNICACIÓN GRÁFICA Y PUBLICITARIA 2024": "Auxiliar de Diseño grafico",
    "TÉCNICAS IUDC OPERACIONES DE SOFTWARE Y REDES DE COMPUTO 2024": "Auxiliar en Asistencia y Soporte dde Tecnologías de la Información",
    "TÉCNICAS IUDC SALUD OCUPACIONAL 2024": "Seguridad Ocupacional",
    "TÉCNICAS IUDC COCINA NAL E INTERNACIONAL 2024": "Cocina Internacional",
    "TÉCNICAS IUDC EN DISEÑO DE MODAS 2024": "Auxiliar de Corte y Confección",
    "TÉCNICAS IUDC ANIMACION DIGITAL 2024": "Auxiliar de Ingeniería en Edición",
    "TÉCNICAS IUDC JUDICIAL Y CRIMINALISTICA 2024": "Investigadores Judiciales y Criminalísticos",
    "TÉCNICAS IUDC AUXILIAR ADMINISTRATIVO 2024": "Auxiliar Administrativo",
    "TÉCNICAS IUDC CLINICA VETERINARIA Y CUIDADO DE MASCOTAS- 2024": "Auxiliar en Clínica Veterinaria",
    "TÉCNICAS IUDC CONTABLE Y FINANCIERO 2024": "Auxiliar Contable y Financiero",
    "TÉCNICAS IUDC ENFERMERIA 2024": "Auxiliar en Enfermería",
    "TÉCNICAS IUDC RECURSOS HUMANOS 2024": "Auxiliar en Talento Humano",

    // Posgrados
    "Postgrado en Derecho Administrativo y Contractual IUDC 2024": "Especialización en Derecho Administrativo y Contractual",
    "Postgrado en Derecho Penal y Criminalistica 2024": "Especialización en Derecho Penal y Criminalística ",
    "Postgrado en Gerencia de Empresas 2024": "Especialización en Gerencia de Empresas",
    "Postgrado en Gerencia Financiera 2024": "Especialización en Gerencia Financiera",
    "Postgrado en Gerencia de Talento Humano 2024": "Especialización en Gerencia de Talento Humano"
};

module.exports = reemplazos;